In [62]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [42]:
df_adnimerge = pd.read_csv('./../../data/tabular/ADNIMERGE.csv') #,dtype={'PTID': str, 'VISCODE': str, 'IMAGEUID': str})
df_adnimerge.rename(columns={'PTID': 'SUBJECT', 'IMAGEUID': 'IMAGE_DATA_ID'}, inplace=True)
df_adnimerge['IMAGE_DATA_ID'] = 'I' + df_adnimerge['IMAGE_DATA_ID'].fillna(999999).astype(int).astype(str)
print(df_adnimerge.shape)
display(df_adnimerge.head(5))

(15836, 44)

,RID,SUBJECT,VISCODE,SITE,COLPROT,ORIGPROT,EXAMDATE,IMAGE_DATA_ID,DX,DX_bl,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,CDRSB,ADAS11,ADAS13,ADASQ4,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,LDELTOTAL,DIGITSCOR,TRABSCOR,FAQ,MOCA,EcogPtMem,EcogPtLang,EcogPtVisspat,EcogPtPlan,EcogPtOrgan,EcogPtDivatt,EcogPtTotal,EcogSPMem,EcogSPLang,EcogSPVisspat,EcogSPPlan,EcogSPOrgan,EcogSPDivatt,EcogSPTotal
0,2,011_S_0002,bl,107.0,ADNI1,ADNI1,2005-09-29,I35475,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,NaN,10.67,18.67,5.0,NaN,44.0,4.0,6.0,54.545455,NaN,34.0,112.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6210,014_S_6210,sc,11.0,ADNI3,ADNI3,2014-02-14,I969431,CN,CN,63.0,Female,16.0,Not Hisp/Latino,White,Widowed,0.5,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6237,153_S_6237,sc,57.0,ADNI3,ADNI3,2018-02-15,I970943,CN,CN,61.0,Female,20.0,Not Hisp/Latino,Asian,Married,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1286,100_S_1286,init,41.0,ADNI3,ADNI1,2018-02-07,I959489,CN,CN,76.0,Female,19.0,Not Hisp/Latino,White,Divorced,0.0,4.67,6.67,1.0,29.0,54.0,7.0,2.0,15.384615,18.0,NaN,79.0,0.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6165,100_S_6165,sc,41.0,ADNI3,ADNI3,2018-02-16,I999999,MCI,MCI,72.0,Female,14.0,Not Hisp/Latino,White,Divorced,1.5,NaN,NaN,NaN,26.0,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df_selected_mris = pd.read_csv('./../../data/reference/REFERENCE_TABLE_FOR_MRI.csv')
print(df_selected_mris.shape)
display(df_selected_mris.head(5))

(10002, 10)

,SUBJECT_IMAGE_ID,IMAGE_DATA_ID,SUBJECT,GROUP,MACRO_GROUP,SEX,AGE,VISIT,ACQ_DATE,DESCRIPTION
0,002_S_0295#I118671,I118671,002_S_0295,CN,CN,M,85,sc,2006-04-18,MPR; GradWarp; B1 Correction; N3; Scaled_2
1,002_S_0295#I118692,I118692,002_S_0295,CN,CN,M,85,m06,2006-11-02,MPR; GradWarp; B1 Correction; N3; Scaled_2
2,002_S_0295#I64025,I64025,002_S_0295,CN,CN,M,86,m12,2007-05-25,MPR; GradWarp; B1 Correction; N3; Scaled
3,002_S_0295#I123685,I123685,002_S_0295,CN,CN,M,87,m24,2008-07-23,MPR; GradWarp; B1 Correction; N3; Scaled
4,002_S_0295#I150177,I150177,002_S_0295,CN,CN,M,88,m36,2009-05-22,MPR; GradWarp; B1 Correction; N3; Scaled

In [51]:
df_adnimerge.IMAGE_DATA_ID.unique().shape

(10067,)

In [52]:
df_selected_mris.IMAGE_DATA_ID.unique().shape

(10002,)

In [53]:
df_downloaded_mris = pd.read_csv('./../../data/reference/DOWNLOAD_RAW_MRI.csv')
print(df_downloaded_mris.shape)
display(df_downloaded_mris.head(5))

(7205, 6)

,SUBJECT,IMAGE_DATA_ID,IMAGE_NAME,FORMAT,N_FILES,PATH
0,002_S_0295,I118671,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correction__N3__Scaled_2_Br_20081001114556321_S13408_I118671.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/002_S_0295/MPR__GradWarp__B1_Correction__N3__Scaled_2/2006-04-18_08_20_30.0/I118671
1,002_S_0295,I123685,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20081026123329555_S54061_I123685.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/002_S_0295/MPR__GradWarp__B1_Correction__N3__Scaled/2008-07-23_14_51_41.0/I123685
2,002_S_0295,I150177,ADNI_002_S_0295_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20090723154406768_S67612_I150177.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/002_S_0295/MPR__GradWarp__B1_Correction__N3__Scaled/2009-05-22_07_00_57.0/I150177
3,002_S_0295,I291867,ADNI_002_S_0295_MR_MT1__GradWarp__N3m_Br_20120322162736575_S84944_I291867.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/002_S_0295/MT1__GradWarp__N3m/2010-05-13_06_37_21.0/I291867
4,002_S_0413,I11128519,ADNI_002_S_0413_MR_Accelerated_Sagittal_MPRAGE_(MSV21)__br_raw_20250226190620274_90.dcm,dcm,208,/mnt/d/lucas/Downloads/raw/ADNI/002_S_0413/Accelerated_Sagittal_MPRAGE__MSV21_/2025-02-19_10_21_54.0/I11128519

In [54]:
df_filtered_mris = df_adnimerge.merge(df_downloaded_mris, on=['SUBJECT', 'IMAGE_DATA_ID'], how='inner')
df_filtered_mris.shape

(7996, 48)

In [63]:
df_filtered_mris

,RID,SUBJECT,VISCODE,SITE,COLPROT,ORIGPROT,EXAMDATE,IMAGE_DATA_ID,DX,DX_bl,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,CDRSB,ADAS11,ADAS13,ADASQ4,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,LDELTOTAL,DIGITSCOR,TRABSCOR,FAQ,MOCA,EcogPtMem,EcogPtLang,EcogPtVisspat,EcogPtPlan,EcogPtOrgan,EcogPtDivatt,EcogPtTotal,EcogSPMem,EcogSPLang,EcogSPVisspat,EcogSPPlan,EcogSPOrgan,EcogSPDivatt,EcogSPTotal,IMAGE_NAME,FORMAT,N_FILES,PATH
0,2,011_S_0002,bl,107.0,ADNI1,ADNI1,2005-09-29,I35475,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,NaN,10.67,18.67,5.0,NaN,44.0,4.0,6.0,54.545455,NaN,34.0,112.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_011_S_0002_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070108225928642_S9107_I35475.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/011_S_0002/MPR__GradWarp__B1_Correction__N3__Scaled/2005-08-26_08_45_00.0/I35475
1,2,011_S_0002,init,8.0,ADNI3,ADNI1,2017-11-01,I35475,MCI,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,2.5,17.67,28.67,8.0,23.0,35.0,4.0,3.0,37.500000,11.0,NaN,229.0,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_011_S_0002_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070108225928642_S9107_I35475.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/011_S_0002/MPR__GradWarp__B1_Correction__N3__Scaled/2005-08-26_08_45_00.0/I35475
2,6210,014_S_6210,sc,11.0,ADNI3,ADNI3,2014-02-14,I969431,CN,CN,63.0,Female,16.0,Not Hisp/Latino,White,Widowed,0.5,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_014_S_6210_MR_Accelerated_Sagittal_MPRAGE__br_raw_20180302150140607_44_S663485_I969431.dcm,dcm,176,/mnt/d/lucas/Downloads/raw/ADNI/014_S_6210/Accelerated_Sagittal_MPRAGE/2018-03-02_07_59_29.0/I969431
3,6237,153_S_6237,sc,57.0,ADNI3,ADNI3,2018-02-15,I970943,CN,CN,61.0,Female,20.0,Not Hisp/Latino,Asian,Married,0.0,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_153_S_6237_MR_Accelerated_Sagittal_MPRAGE__br_raw_20180307135252368_4_S664777_I970943.dcm,dcm,176,/mnt/d/lucas/Downloads/raw/ADNI/153_S_6237/Accelerated_Sagittal_MPRAGE/2018-02-27_07_18_32.0/I970943
4,6237,153_S_6237,bl,57.0,ADNI3,ADNI3,2018-04-12,I970943,CN,CN,61.0,Female,20.0,Not Hisp/Latino,Asian,Married,NaN,3.00,5.00,2.0,NaN,45.0,7.0,9.0,69.230769,NaN,NaN,62.0,0.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_153_S_6237_MR_Accelerated_Sagittal_MPRAGE__br_raw_20180307135252368_4_S664777_I970943.dcm,dcm,176,/mnt/d/lucas/Downloads/raw/ADNI/153_S_6237/Accelerated_Sagittal_MPRAGE/2018-02-27_07_18_32.0/I970943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7991,4102,072_S_4102,v05,34.0,ADNI2,ADNI2,2012-01-17,I377488,MCI,MCI,67.0,Female,14.0,Not Hisp/Latino,White,Married,3.0,26.67,30.67,4.0,25.0,32.0,3.0,6.0,85.714286,NaN,NaN,120.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_072_S_4102_MR_MT1__GradWarp__N3m_Br_20130620123053611_S172231_I377488.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/072_S_4102/MT1__GradWarp__N3m/2012-01-17_14_33_36.0/I377488
7992,886,130_S_0886,v06,50.0,ADNI2,ADNI1,2012-02-06,I297860,CN,CN,71.0,Female,15.0,Not Hisp/Latino,White,Married,0.0,5.67,7.67,2.0,30.0,42.0,2.0,0.0,0.000000,9.0,NaN,72.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_130_S_0886_MR_MT1__N3m_Br_20120417150620932_S130302_I297860.nii,nii,1,/mnt/d/lucas/Downloads/raw/ADNI/130_S_0886/MT1__N3m/2011-11-17_13_10_42.0/I297860
7993,2373,130_S_2373,y4,50.0,ADNI3,ADNIGO,NaN,I1459838,Dementia,MCI,79.0,Female,13.0,Not Hisp/Latino,White,Married,6.0,24.00,35.00,10.0,20.0,22.0,-1.0,4.0,100.000000,0.0,NaN,112.0,24.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_130_S_2373_MR_Sagittal_3D_Accelerated_MPRAGE_br_raw_20210624115227917_10_S1037085_I1459838.dcm,dcm,211,/mnt/d/lucas/Downloads/raw/ADNI/130_S_2373/Sagittal_3D_Accelerated_MPRAGE/2021-06-23_15_46_13.0/I1459838
7994,5285,051_S_5285,init,29.0,ADNI3,ADNI2,NaN,I1055626,Dementia,CN,71.0,Male,16.0,Not Hisp/Latino,More than one,Divorced,NaN,12.00,18.00,4.0,29.0,25.0,2.0,1.0,16.666667,9.0,NaN,165.0,6.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_051_S_5285_MR_Accelerated_Sagittal_MPRAGE__br_raw_20181003151207098_158_S732945_I1055626.dcm,dcm,208,/mnt/d/lucas/Downloads/raw/ADNI/051_S_5285/Accelerated_Sagittal_MPRAGE/2018-10-02_13_15_29.0/I1055626
7995,6073,012_S_6073,y3,9.0,ADNI3,ADNI3,NaN,I1404918,Dementia,MCI,63.0,Male,17.0,Not Hisp/Latino,White,Married,NaN,53.33,67.33,9.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADNI_012_S_6073_MR_Accelerated_Sagittal_MPRAGE__br_raw_20210128172041216_48_S996833_I1404918.dcm,dcm,176,/mnt/d/lucas/Downloads/raw/ADNI/012_S_6073/Accelerated_Sagittal_MPRAGE/2021-01-13_09_29_38.0/I1404918

In [65]:
df_adnimerge.query("SUBJECT == '011_S_0002'").sort_values('EXAMDATE')

,RID,SUBJECT,VISCODE,SITE,COLPROT,ORIGPROT,EXAMDATE,IMAGE_DATA_ID,DX,DX_bl,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,CDRSB,ADAS11,ADAS13,ADASQ4,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,LDELTOTAL,DIGITSCOR,TRABSCOR,FAQ,MOCA,EcogPtMem,EcogPtLang,EcogPtVisspat,EcogPtPlan,EcogPtOrgan,EcogPtDivatt,EcogPtTotal,EcogSPMem,EcogSPLang,EcogSPVisspat,EcogSPPlan,EcogSPOrgan,EcogSPDivatt,EcogSPTotal
0,2,011_S_0002,bl,107.0,ADNI1,ADNI1,2005-09-29,I35475,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,NaN,10.67,18.67,5.0,NaN,44.0,4.0,6.0,54.545455,NaN,34.0,112.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10365,2,011_S_0002,m06,107.0,ADNI1,ADNI1,2006-03-06,I999999,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,0.0,10.67,19.67,7.0,28.0,40.0,3.0,3.0,37.500000,NaN,28.0,125.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8187,2,011_S_0002,m36,107.0,ADNI1,ADNI1,2008-08-27,I999999,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,0.0,12.00,20.00,5.0,29.0,34.0,2.0,7.0,87.500000,13.0,33.0,127.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9233,2,011_S_0002,m60,8.0,ADNIGO,ADNI1,2010-09-27,I999999,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,0.0,13.67,22.67,6.0,28.0,37.0,5.0,4.0,40.000000,12.0,NaN,166.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14240,2,011_S_0002,v06,8.0,ADNI2,ADNI1,2011-09-19,I999999,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,0.0,12.00,21.00,6.0,23.0,42.0,3.0,5.0,55.555556,14.0,NaN,64.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12066,2,011_S_0002,v11,8.0,ADNI2,ADNI1,2012-10-04,I999999,MCI,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,1.0,9.00,14.00,3.0,24.0,37.0,5.0,7.0,70.000000,10.0,NaN,133.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2685,2,011_S_0002,v21,8.0,ADNI2,ADNI1,2013-09-23,I999999,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,0.5,10.00,18.00,5.0,25.0,38.0,3.0,6.0,66.666667,12.0,NaN,167.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3175,2,011_S_0002,v41,8.0,ADNI2,ADNI1,2015-10-20,I999999,CN,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,0.0,12.33,20.33,5.0,28.0,34.0,5.0,8.0,80.000000,12.0,NaN,162.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,2,011_S_0002,v51,8.0,ADNI2,ADNI1,2016-10-03,I999999,MCI,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,1.0,11.67,19.67,5.0,24.0,37.0,3.0,10.0,100.000000,13.0,NaN,169.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,2,011_S_0002,init,8.0,ADNI3,ADNI1,2017-11-01,I35475,MCI,CN,74.0,Male,16.0,Not Hisp/Latino,White,Married,2.5,17.67,28.67,8.0,23.0,35.0,4.0,3.0,37.500000,11.0,NaN,229.0,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df_filtered_mris.groupby(['ORIGPROT']).agg({'SUBJECT': 'nunique', 'IMAGE_DATA_ID': 'nunique'}).sort_values('ORIGPROT', ascending=True)

          SUBJECT  IMAGE_DATA_ID
ORIGPROT
ADNI1         740           2642
ADNI2         646           1832
ADNI3         786           1734
ADNI4         569            599
ADNIGO        118            398